// <auto-generated />

using System.Resources;
using System.Globalization;

namespace DurableTask.Hosting.Properties
{
    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("DurableTask.Hosting.Properties.Strings", typeof(Strings).Assembly);

        /// <summary>
        ///     Unable to gracefully shutdown task hub worker in time.
        /// </summary>
        public static string ForcedShutdown
            => GetString("ForcedShutdown");

        /// <summary>
        ///     Starting task hub worker.
        /// </summary>
        public static string TaskHubWorkerStarting
            => GetString("TaskHubWorkerStarting");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}
