// <auto-generated />

using System.Resources;
using System.Globalization;

namespace DurableTask.Extensions.Properties
{
    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("DurableTask.Extensions.Properties.Strings", typeof(Strings).Assembly);

        /// <summary>
        ///     Expected DataConverter to be of or derived from type '{expected}', but instead found type '{actual}'.
        /// </summary>
        public static string InvalidDataConverterType(object expected, object actual)
            => string.Format(
                GetString("InvalidDataConverterType", nameof(expected), nameof(actual)),
                expected, actual,
                CultureInfo.CurrentUICulture);

        /// <summary>
        ///     Expected a non-null descriptor from the provided request.
        /// </summary>
        public static string NullDescriptor
            => GetString("NullDescriptor");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}
